### ISSUE TITLE
Need steps to run client and server sample program in different machines

### ISSUE THREAD

**Issue by kunchumraghu** [Juniper/grpc-c#10]
Hi ajhai,

In the sample program, I want to run foo_client and foo_server in different machine and should talk to each other. Can you please let me know the steps to do that.

Thanks and Regards
Raghu. S

**Comment by ajhai** [comment]
You can use grpc_c_server_add_insecure_http2_port(server, "IP:PORT"); to run your server on IP:PORT. Look at examples/foo_server.c. So if you run it on 0.0.0.0:30000, you will able to reach your server from other machines. For running client on a different machine, you will need to make some changes to lib. Please wait for me to push some changes which will add new API that will enable this.

**Comment by shadansari** [comment]
Hi Ajay, could you point to the lib / file / code segment where the change is required to support external client connectivity. [https://github.com/kunchumraghu](kunchumraghu) and I are working on an open-source project (https://github.com/opencord/voltha) where we plan to use your library. We can help with adding/testing this support.

**Comment by kunchumraghu** [comment]
Hi Ajay,

Thanks for reply.  For a time being, i did below changes in client.c and client could able to establish the connection with remote server. I will wait for you APIS. Once it is available we will merge those changes.

In the below changes the "grpc_c_client_init" is called with server name = <IPaddress:Port_Number>

root@grpc-VirtualBox:/home/grpc/ATT/grpc-c/build/examples# git diff  ../../lib/client.c
diff --git a/lib/client.c b/lib/client.c
index 24926a6..9f02134 100644
--- a/lib/client.c
+++ b/lib/client.c
@@ -134,8 +134,10 @@ grpc_c_client_init (const char *server_name, const char *client_id,
     }
 
     bzero(buf, BUFSIZ);
-    snprintf_safe(buf, sizeof(buf), "%s%s", PATH_GRPC_C_DAEMON_SOCK, 
-                 server_name);
+    /* snprintf_safe(buf, sizeof(buf), "%s%s", PATH_GRPC_C_DAEMON_SOCK, 
+                 server_name); */
+
+    snprintf_safe(buf, sizeof(buf), "%s", server_name);
     if (buf[0] == '\0') {
        return NULL;
     }

**Comment by ajhai** [comment]
@kunchumraghu that should do it for now. I'm adding a new API where you can call grpc_c_client_init_by_host to use fully built address string.

**Comment by ajhai** [comment]
@kunchumraghu I have added grpc_c_client_init_by_host and you can refer to its usage as part of changes I pushed with a0dc4ab. You can also look at https://github.com/Juniper/grpc-c/blob/master/lib/h/grpc-c/grpc-c.h#L297
