### ISSUE TITLE
syntax error near unexpected token `PROTOBUF_C,'

### ISSUE THREAD

**Issue by brianLeeson** [Juniper/grpc-c#13]
after `make` step in installation
```
checking for unistd.h... (cached) yes
checking grpc/grpc.h usability... yes
checking grpc/grpc.h presence... yes
checking for grpc/grpc.h... yes
../configure: line 16221: syntax error near unexpected token `PROTOBUF_C,'
../configure: line 16221: `PKG_CHECK_MODULES(PROTOBUF_C, libprotobuf-c >= 1.2.1)'

```

I apologize if this this too simple! My guess is that I have made a mistake installing the protocol buffers.  Looking at the dependencies:
**gRPC v1.3.0**
Use correct version:
`git checkout -b test v1.3.0`
Then followed [install.md](https://github.com/grpc/grpc/blob/v1.3.0/INSTALL.md)

**protobuf 3.0
protobuf-c 1.2.1**
I am not sure of the steps to meet these requirements.  Does the Makefile install them for me as the Protoc section seems to suggest? Is this a separate step? Is not related to the problem that I am having?

**Comment by ajhai** [comment]
Can you install protobuf-c from third_party? Before make, goto third_party/protobuf-c and do configure, make and make install.. then do make from top level
