### ISSUE TITLE
Query regarding usage of bytes in grpc-c 

### ISSUE THREAD

**Issue by kunchumraghu** [Juniper/grpc-c#17]
Hi Ajay,

I am using a bytes in proto and allocating memory(using malloc) while sending raw bytes to peer. Will GRPC-C free this memory or does application should free it.

Thanks and Regards
Raghu. S

**Comment by ajhai** [comment]
Hi Raghu,

 Application will have to free this data. grpc-c will free just the context and other internal structures.

Thanks.
