### ISSUE TITLE
TLS  Support for gRPC Client & Server ?

### ISSUE THREAD

**Issue by Sisir-Chowdhury** [Juniper/grpc-c#18]
Does this Library Support TLS  for gRPC Client & Server ? 

Sisir.

**Comment by ajhai** [comment]
Yeah. It does support TLS for client and server. https://github.com/Juniper/grpc-c/blob/master/lib/h/grpc-c/grpc-c.h#L615 where creds can be created with something like https://github.com/grpc/grpc/blob/master/include/grpc/grpc_security.h#L331 . Similar you can do for client as well.
