### ISSUE TITLE
extra "uint32_t flags" in generated client code

### ISSUE THREAD

**Issue by zwumdd** [Juniper/grpc-c#28]
Hi Ajay,

I tried the steps, the generated foo.grpc-c.h file has an extra "uint32_t flags" parameter (6 params total), however the caller does not (5 params total), resulting in the following compile error:

foo.grpc-c.h:

int foo__greeter__say_hello (grpc_c_client_t *client, grpc_c_metadata_array_t *a
rray, uint32_t flags, Foo__HelloRequest *input, Foo__HelloReply **output, grpc_c
_status_t *status, long timeout);

../../examples/foo_client.c:46:18: error: too few arguments to function ‘foo__greeter__say_hello’
     int status = foo__greeter__say_hello(client, NULL, &h, &r, NULL, -1);

**Comment by zwumdd** [comment]
also _write and _finish have similar issues:

../../examples/foo_server.c:50:10: error: too few arguments to function ‘context->gcc_stream->write’
     if (!context->gcc_stream->write(context, &r, -1)) {

../../examples/foo_server.c:63:9: error: too few arguments to function ‘context->gcc_stream->finish’
     if (context->gcc_stream->finish(context, &status)) {

**Comment by ajhai** [comment]
Commit 1aa14a9 updates examples with new API.
