### ISSUE TITLE
build failed on ubuntu 16.04

### ISSUE THREAD

**Issue by cogmeta** [Juniper/grpc-c#32]
make  all-recursive
make[1]: Entering directory '/code/cogmeta/vendor/grpc-c/build'
Making all in compiler
make[2]: Entering directory '/code/cogmeta/vendor/grpc-c/build/compiler'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/code/cogmeta/vendor/grpc-c/build/compiler'
Making all in lib
make[2]: Entering directory '/code/cogmeta/vendor/grpc-c/build/lib'
depbase=`echo client.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../lib -I..    -I../../lib -I../../lib/h -I../../l\
ib/../third_party/protobuf-c -g -O2 -MT client.lo -MD -MP -MF $depbase.Tpo -c -o client.lo ../../lib/client.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../lib -I.. -I../../lib -I../../lib/h -I../../lib/../third_party/protobuf-c -g \
-O2 -MT client.lo -MD -MP -MF .deps/client.Tpo -c ../../lib/client.c  -fPIC -DPIC -o .libs/client.o
../../lib/client.c: In function ‘gc_client_create_by_host’:
../../lib/client.c:82:43: error: too few arguments to function ‘grpc_completion_queue_create’
     client->gcc_channel_connectivity_cq = grpc_completion_queue_create(NULL);
                                           ^
In file included from ../../lib/h/grpc-c/grpc-c.h:14:0,
                 from ../../lib/client.c:6:
/usr/local/include/grpc/grpc.h:98:32: note: declared here

**Comment by ajhai** [comment]
Looks like you are grpc version mismatch. Can you follow given build instructions? Git submodule update will take care of pulling matching grpc version into third_party/

```
autoreconf --install
git submodule update --init
./builddeps.sh
```

**Comment by cogmeta** [comment]
No Luck. Ended up using the official grpc c++ api.
