### ISSUE TITLE
grpc-c supported Streaming RPCs ？

### ISSUE THREAD

**Issue by lifeng68** [Juniper/grpc-c#4]
Is grpc-c supported  a server-side streaming RPC ？Can you update a server-side streaming RPC example，THX？

**Comment by ajhai** [comment]
@lifeng68  we do support server-side streaming and client-side streaming is underway. This is still work in progress. I will update example and close this issue once done.

**Comment by lifeng68** [comment]
Ok,thanks very much.

**Comment by lifeng68** [comment]
Are there any new developments on server-side streaming RPC？

**Comment by ajhai** [comment]
@lifeng68 Yes. I'm changing the API slightly. Will let you know once I add some examples and push those changes

**Comment by steiler** [comment]
@ajhai I'm actually trying to make use of gRPC in Python as well as using the open-nti-input-oc Project.
Utilizing a vMX 17.1 I always catch the following error:
`JGrpcServer: Unknown RPC /Telemetry.OpenConfigTelemetry/telemetrySubscribe received`
I do somehow beleave the _na-openconfig-telemetry.proto_ has changed from what is listed under:
http://www.juniper.net/documentation/en_US/junos/topics/reference/general/grpc-service-definition-junos-telemetry-interface.html
Can you confirm so? Where can I retrieve the actual one? Or do I have to use the official OpenConfig .protos?

Thanks,
Markus

**Comment by ajhai** [comment]
@steiler Please check if you have installed Junos network agent package on your vMX. You can download it from https://webdownload.juniper.net/swdl/dl/secure/site/1/record/66315.html .

**Comment by steiler** [comment]
I've already installed that package. The error shows up nevertheless.
Please find some output in the following pastebin.
https://pastebin.com/MtHdRdM0

**Comment by ajhai** [comment]
@lifeng68 Please take a look at updated examples. You can also look at test/end2end/ .
