### ISSUE TITLE
Build Fail on Ubuntu 16.04 

### ISSUE THREAD

**Issue by mankash** [Juniper/grpc-c#5]
Hello : 

I followed the instructions to build this repo without success. 

Please find my build failure output attached.

Thanks
[Grpc-C-BuildLog.txt](https://github.com/Juniper/grpc-c/files/953423/Grpc-C-BuildLog.txt)

**Comment by ajhai** [comment]
What version of gRPC are you using?

**Comment by mankash** [comment]
Using v 1.2.0 Commit ID: e2cfe9df79c4eda4e376222df064c4c65e616352
Link to commit: https://github.com/grpc/grpc/commit/e2cfe9df79c4eda4e376222df064c4c65e616352

**Comment by lifeng68** [comment]
```
protobuf  tag：3.2.1  
protobuf-c tag：1.2.1  
gRPC tag ：1.1.3
```
@mankash I used these version ,it works, hope to help you

**Comment by mankash** [comment]
Hello @ajhai - was your team able to reproduce the issue?

@lifeng68  - I'm unable to build even with the versions you've tagged. What's your gcc/g++ versions? What host OS and kernel are you on (I doubt this has an impact, but never hurts to ask)?

Thanks

**Comment by shadansari** [comment]
@mankash - I was able to compile and run the examples after fixing the compile errors. You can try this patch:

https://github.com/Juniper/grpc-c/pull/6/commits/353b40cd920cd749ed6cf71f8df17f1d5cf2c89d

@ajhai - I have created a pull request.

**Comment by shadansari** [comment]
[](https://github.com/Juniper/grpc-c/pull/6/commits/353b40cd920cd749ed6cf71f8df17f1d5cf2c89d)

**Comment by shadansari** [comment]
https://github.com/Juniper/grpc-c/pull/6/commits/353b40cd920cd749ed6cf71f8df17f1d5cf2c89d

**Comment by shadansari** [comment]
@mankash - I was able to get past the compile errors and try out the example after making the following fix:

https://github.com/Juniper/grpc-c/pull/6/commits/353b40cd920cd749ed6cf71f8df17f1d5cf2c89d

**Comment by shadansari** [comment]
My grpc version is v1.1.3.

**Comment by lifeng68** [comment]
@mankash - The patch from shadansari should solve your problem.

353b40c

**Comment by ajhai** [comment]
@mankash I'm moving grpc-c to use gRPC 1.3.0. You should check once the changes are pushed.

**Comment by brianLeeson** [comment]
@shadansari How are you running an older version of grpc? The instructions that I have found in INSTRUCTIONS are for the latest 1.4 I do see that the older versions are available [here](https://github.com/grpc/grpc/releases), but do not see how I should proceed.

**Comment by ajhai** [comment]
@brianLeeson @mankash Please try latest from this repo with gRPC v1.3.0. It should fix build issues.
