### ISSUE TITLE
What is the use of the generated'has_'

### ISSUE THREAD

**Issue by lifeng68** [Juniper/grpc-c#9]
@ajhai , Hello,  My .proto file defined the message `KillRequest` as below, 
```
message KillRequest {
        string id = 1;
	bool force = 2;
	uint32 timeout = 3;
}
```
I used "make lcrd.grpc-c.c" generated the code, found that the `struct  _KillRequest` has the `protobuf_c_boolean has_force;` and `protobuf_c_boolean has_timeout`.
I want to know why we add these two varibales,and what is the use of them. And I tested the code,found that we must fill them with `true`,otherwise,the grpc server could not recevice the right message. 
I readed the grpc-c code, but i did not quit understand that. Please tell me something about that,THX
```
struct  _KillRequest
{
  ProtobufCMessage base;
  char *id;
  **protobuf_c_boolean has_force;**
  protobuf_c_boolean force;
  **protobuf_c_boolean has_timeout;**
  uint32_t timeout;
};
```

**Comment by ajhai** [comment]
@lifeng68 this is proto2 and is coming from protobuf-c. Please refer to this SO answer https://stackoverflow.com/a/9207110
